services:
  postgres:
    image: postgres:15-alpine
    container_name: nps_postgres
    environment:
      POSTGRES_DB: nps_db
      POSTGRES_USER: nps_user
      POSTGRES_PASSWORD: nps_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nps_user -d nps_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    container_name: nps_backend
    environment:
      DATABASE_URL: postgresql://nps_user:nps_password@postgres:5432/nps_db
      CORS_ORIGINS: http://localhost:3000
      SECRET_KEY: super-secret-key
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: ./front-end
    container_name: nps_frontend
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
